language: node_js

node_js:
  - 0.10

install:
  - npm install
  - npm install karma-cli    # Installed globally in local
  - npm install protractor   # Installed globally in local

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run start-test > /dev/null &
  - npm run update-webdriver
  - sleep 2 # give server time to start

script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --browsers=Firefox
  - node_modules/.bin/protractor tests/protractor.conf.js --browser=firefox

#deploy:
#  provider: heroku
#  api_key: XXX
#  app: leejefon-project-catelog
